export const sortData = {
  tasks: {
    'task-1': { id: 'task-1', content: 'Importance of card sorting' },
    'task-2': { id: 'task-2', content: 'Watch my favorite show' },
    'task-3': { id: 'task-3', content: 'Charge my phone' },
    'task-4': { id: 'task-4', content: 'Cook dinner for the visitors' },
    'task-5': { id: 'task-5', content: 'Do the dishes by noon' },
    'task-6': { id: 'task-6', content: 'Do the kiddies laundry' },
    'task-7': { id: 'task-7', content: 'Take out the garbage' },
    'task-8': { id: 'task-8', content: 'Terms of use of service' },
    'task-9': { id: 'task-9', content: 'Shop for groceries' },
    'task-10': { id: 'task-10', content: 'Hail a taxi down the tunnel' },
    'task-11': { id: 'task-11', content: 'Build a beautiful web application' },
    'task-12': { id: 'task-12', content: 'Analyze the data fetched from the DB' },
    'task-13': { id: 'task-13', content: 'Build a user friendly UI' },
    'task-14': { id: 'task-14', content: 'Build a beautiful mobile application' },
    'task-15': { id: 'task-15', content: 'Write a user friendly documentation' },
    'task-16': { id: 'task-16', content: 'Create a pipeline for the CI/CD' },
  },
  columns: {
    'column-1': {
      id: 'column-1',
      title: 'Card List',
      taskIds: [
        'task-1',
        'task-2',
        'task-3',
        'task-4',
        'task-5',
        'task-6',
        'task-7',
        'task-8',
        'task-9',
        'task-10',
        'task-11',
        'task-12',
        'task-13',
        'task-14',
        'task-15',
        'task-16',
      ],
    },
    'column-2': {
      id: 'column-2',
      title: 'Title-2',
      taskIds: [],
      paperVisibility: false,
      cardVisibility: false,
    },
    'column-3': {
      id: 'column-3',
      title: 'Title-3',
      taskIds: [],
      paperVisibility: false,
      cardVisibility: false,
    },
    'column-4': {
      id: 'column-4',
      title: 'Title-4',
      taskIds: [],
      paperVisibility: false,
      cardVisibility: false,
    },
    'column-5': {
      id: 'column-5',
      title: 'Title-5',
      taskIds: [],
      paperVisibility: false,
      cardVisibility: false,
    },
    'column-6': {
      id: 'column-6',
      title: 'Title-6',
      taskIds: [],
      paperVisibility: false,
      cardVisibility: false,
    },
    'column-7': {
      id: 'column-7',
      title: 'Title-7',
      taskIds: [],
      paperVisibility: false,
      cardVisibility: false,
    },
    'column-8': {
      id: 'column-8',
      title: 'Title-8',
      taskIds: [],
      paperVisibility: false,
      cardVisibility: false,
    },
    'column-9': {
      id: 'column-9',
      title: 'Title-9',
      taskIds: [],
      paperVisibility: false,
      cardVisibility: false,
    },
    'column-10': {
      id: 'column-10',
      title: 'Title-10',
      taskIds: [],
      paperVisibility: false,
      cardVisibility: false,
    },
  },
  // Facilitate reordering of the columns
  mainColumn: [ 'column-1'],
  columnOrder: [ 'column-2', 'column-3', 'column-4', 'column-5', 'column-6', 'column-7', 'column-8', 'column-9', 'column-10'],
};